// 상수 정의
const BULK_PURCHASE_THRESHOLD = 30;
const BULK_PURCHASE_ITEM_THRESHOLD = 10;
const BULK_DISCOUNT_RATE = 0.25;
const TUESDAY_DISCOUNT_RATE = 0.1;
const POINTS_PER_AMOUNT = 1000;
const LOW_STOCK_THRESHOLD = 5;
const FLASH_SALE_INTERVAL = 30000;
const FLASH_SALE_DISCOUNT_RATE = 0.2;
const RECOMMENDATION_INTERVAL = 60000;
const RECOMMENDATION_DISCOUNT_RATE = 0.05;

const PRODUCT_BULK_DISCOUNTS = {
  p1: 0.1,
  p2: 0.15,
  p3: 0.2,
  p4: 0.05,
  p5: 0.25
};

export {
  BULK_PURCHASE_THRESHOLD,
  BULK_PURCHASE_ITEM_THRESHOLD,
  BULK_DISCOUNT_RATE,
  TUESDAY_DISCOUNT_RATE,
  POINTS_PER_AMOUNT,
  LOW_STOCK_THRESHOLD,
  FLASH_SALE_INTERVAL,
  FLASH_SALE_DISCOUNT_RATE,
  RECOMMENDATION_INTERVAL,
  RECOMMENDATION_DISCOUNT_RATE,
  PRODUCT_BULK_DISCOUNTS
};
